OPM/IFEM-OpenFrac

CMakeLists.txt
CahnHilliard.C
CahnHilliard.h
FractureElasticity.C
FractureElasticity.h
SIMDynElasticity.h
SIMFractureDynamics.h
SIMPhaseField.h
Test/Rectangle-p1.xinp
Test/Short10x20-adap_FD.reg
Test/Short10x20-p1-adap.xinp
Test/Short10x20-p1.xinp
Test/Short10x20_FD.reg
main_CahnHilliard.C
main_FractureDynamics.C

Vi prøver igjen..
jenkins build this ifem=8 please

Adaptive shared

---

SIMDynElasticity.h
SIMPhaseField.h
Test/Short10x20-adap_FD.reg
Test/Short10x20_FD.reg

Changed: SIM::setInitialConditions has been replaced by a member method.

---

FractureElasticity.C
FractureElasticityVoigt.C
SIMPhaseField.h
Test/Rectangle-p2_CH.reg
Test/Rectangle-p2_penalty_CH.reg
Test/Short10x20-adap_FD.reg
Test/Short10x20_FD.reg

To be merged with OPM/IFEM#112

Isotropic degrading fix + formatting changes

---

main_CahnHilliard.C
main_FractureDynamics.C

Downstream of https://github.com/OPM/IFEM/pull/137

adjust to restart support

---

main_CahnHilliard.C
main_FractureDynamics.C

Changed: handleDataOutput is now a SIMSolver member

---

CMakeLists.txt
CahnHilliard.h
FractureElasticity.h
FractureElasticityVoigt.h
SIMDynElasticity.h
SIMFractureDynamics.h
main_FractureDynamics.C

Downstream of https://github.com/OPM/IFEM/pull/151

Small fixes for portland compiler

---

CahnHilliard.C
CahnHilliard.h
FractureElasticity.C
FractureElasticity.h
FractureElasticityVoigt.C
SIMDynElasticity.h

Think this corresponds better to eq. (5) in Bourdin2012ava which describes the formulation.
Also added: Cut-off value for when the crack pressure should be applied.

Fixed: FractureElasticity::formCrackForce was not right

---

FractureArgs.C
FractureArgs.h
Test/Sneddon-200_FD.reg
Test/Sneddon-200_FD.xinp
main_FractureDynamics.C

Added: Regression test using pre-parsing and crack pressure.

Added: Pre-parsing of input file to read dimension and solver parameters

---

CahnHilliard.h
FractureElasticity.h
FractureElasticityVoigt.h
SIMPhaseField.h
main_FractureDynamics.C

Downstream of OPM/IFEM-Elasticity#55 plus explicit constructors (the items from #25).

Changed: Moved planeStrain option to namespace Elastic

---

PoroFracture.C

Needed for https://github.com/OPM/IFEM-PoroElasticity/pull/37

Changed: Update to new PoroElasticity constructor

---

CMakeLists.txt
CahnHilliard.C
SIMPhaseField.h
Test/Rectangle-p2_CH.hreg
Test/Short10x20-p1-adap.hreg
Test/Sneddon-200_FD.hreg
main_CahnHilliard.C

Downstream of https://github.com/OPM/IFEM/pull/272

update for new hdf5 layout

---

Test/Miehe71-lstatic_FDporo.reg
Test/Miehe71-nocrack_FDporo.reg

Needed for https://github.com/OPM/IFEM-PoroElasticity/pull/38

Changed: Scaling removed upstream

---

Test/Miehe71.xinp
Test/Sneddon-unit.xinp

See https://github.com/OPM/IFEM-PoroElasticity/pull/40

Update to new permeability formulation

---

SIMPhaseField.h

Changed: Use ASMLRSpline instead of ASMunstruct

---

SIMPhaseField.h

Downstream fix associated with OPM/IFEM#353 and VikingScientist/LRsplines#28

Fixed: Crash due to recent update in lrspline library

---

CahnHilliard.C
CahnHilliard.h
SIMDynElasticity.h
Test/Miehe71_FD.reg
Test/ts1-50x40-Miehe_FD.reg

Downstream fix for OPM/IFEM-Elasticity#39

Fixed: Need two solution vectors for correct external energy integration

---

main_CahnHilliard.C
main_FractureDynamics.C

Downstream of https://github.com/OPM/IFEM/pull/433

solver template update - pass appropriate ProcessAdm

---

SIMDynElasticity.h
SIMPhaseField.h

This allows for graph based parallelism.

fixed: add parallel reductions for integration point arrays

---

Test/Sneddon-unit_FDporo.reg

fluid content was added in upstream

fixed: update regression test after upstream addition

---

SIMFractureDynamics.h
SIMFractureQstatic.h
Test/ts1-25x25-5P-adap2-relax-aitken.xinp
Test/ts1-25x25-5P-adap2-relax-aitken_FD.reg

Such that the function-controlled max sub-iterations can be used here also.
Downstream of OPM/IFEM#481

Changed: Using SIMCoupledSI::parseIterations()

---

main_FractureDynamics.C

Fixed: Recalculate tangent matrix for linear solver

---

CMakeLists.txt
SIMPhaseField.C
SIMPhaseField.h
main_CahnHilliard.C

Make SIMPhaseField a private template

---

SIMDynElasticity.h

Downstream of https://github.com/OPM/IFEM-Elasticity/pull/120

add missing header after SIMElasticityWrap refactor

---

FractureElasticity.C
FractureElasticityVoigt.C

Downstream of OPM/IFEM-Elasticity#142

Fixed: Signature change in fromBodyForces() method

---

CahnHilliard.C
CahnHilliard.h
FractureArgs.C
FractureArgs.h
FractureElasticity.C
FractureElasticity.h
PoroFracture.C
PoroFracture.h
SIMDynElasticity.C
SIMDynElasticity.h
SIMExplPhaseField.C
SIMExplPhaseField.h
SIMFractureDynamics.C
SIMFractureDynamics.h
SIMFractureQstatic.C
SIMFractureQstatic.h
SIMPhaseField.C
SIMPhaseField.h
main_FractureDynamics.C

Downstream of https://github.com/OPM/IFEM/pull/661
Downstream of https://github.com/OPM/IFEM-Elasticity/pull/156
Downstream of https://github.com/OPM/IFEM-PoroElasticity/pull/61

changed: tinyxml -> tinyxml2

---

SIMFractureDynamics.C

Fixup for commit c567b9a388cb665a413750e24951c1a88d86b1dd

---

CahnHilliard.C
SIMFractureDynamics.C
SIMPhaseField.C

and some Vector --> Vec3 changes in norm integration for CahnHilliard

Resolve compiler warning from STL

---

FractureElasticity.C
PoroFracture.C
PoroFracture.h

Fixed: The phase-field element vector must be the last item in elmInt.vec

---

PoroFracture.C
PoroFracture.h

Downstream of OPM/IFEM-Elasticity#184

Changed: Remove bool argument in virtual parseMatProp() method

---

SIMPhaseField.C

Downstream of https://github.com/OPM/IFEM/pull/814

prefix LR include paths with LR/

---

Test/TestFractureElasticity.C
Test/TestSIMDynElasticity.C

Downstream of https://github.com/OPM/IFEM/pull/818

add support for catch2 v2
